import Head from 'next/head';
import Image from 'next/image';
import { Footer } from '../components/Footer';
import Navbar from '../components/Navbar';

export default function Home() {
  return (
    <div className="home__container">
      <Navbar />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="home__main">
        <div>
          <div className="home__left-side">
            <h2 className="home__heading">
              Lets become the light of the obscured
            </h2>
            <p className="home__description">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit.
              Suspendisse varius enim in eros elementum tristique. Duis cursus,
            </p>
            <button className="home__button">
              Know More
            </button>
          </div>
          <div></div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
